--- BSDmakefile	Sat Mar  7 02:15:27 2015
+++ GNUmakefile	Sat Mar  7 02:28:02 2015
@@ -1,28 +1,28 @@
-.include "config.mk"
+include config.mk
 
 TIMELOGVER=0
 
 WORKDIR=work
 CFLAGS=-Wall -ansi -pedantic
 
-.ifndef RELEASE
+ifndef RELEASE
 OUTDIR=debug
 CFLAGS+=-O0 -g
-.else
+else
 OUTDIR=dist
-.endif
+endif
 
-.ifdef DARWIN
+ifdef DARWIN
 LIBTIMELOGEXT=dylib
 LIBTIMELOGVEREXT=$(TIMELOGVER).dylib
 LIBTIMELOGSHLIB=-dynamiclib -Wl,-install_name,@loader_path/../lib/libtimelog.$(LIBTIMELOGVEREXT)
 TIMELOGRELOC=
-.else
+else
 LIBTIMELOGEXT=so
 LIBTIMELOGVEREXT=so.$(TIMELOGVER)
 LIBTIMELOGSHLIB=-shared -Wl,-soname,libtimelog.$(LIBTIMELOGVEREXT)
 TIMELOGRELOC=-Wl,-z,origin,-rpath='$$ORIGIN/../lib/'
-.endif
+endif
 
 .PHONY: all
 all: directories $(OUTDIR)/bin/tl
